services:
  backend:
    build: ./spam-sniffer-backend
    container_name: spam-sniffer-backend
    ports:
      - "5000:5000"
    volumes:
      - ./spam-sniffer-backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/spam_sniffer
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./spam-sniffer-frontend
    container_name: spam-sniffer-frontend
    ports:
      - "3000:80"
    volumes:
      - ./spam-sniffer-frontend:/app
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6.0
    container_name: spam-sniffer-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
